### ISSUE TITLE
 Uncaught Exception: Exception: BAD RESPONSE STATUS FROM API (403) in

### ISSUE THREAD

**Issue by azevedown** [WP2Static/static-html-output-plugin#109]
I tried to export my website to S3, but an error occurred 
==> /var/log/nginx/error.log <==
2020/06/17 18:28:24 [error] 4296#0: *4566 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: Exception: BAD RESPONSE STATUS FROM API (403) in /storage/web/wp-content/plugins/static-html-output-plugin/plugin/WP2Static/SitePublisher.php:2

I reinstall the plugin, but the error persists. Somebody get a same error?

tks

**Comment by leonstafford** [comment]
@azevedown you can try the latest build from here: https://github.com/WP2Static/static-html-output-plugin/files/4789479/static-html-output-plugin-6.6.20.zip

(delete old and install/active new). Plugin name has changed to Static HTML Output ahead of next release. 

In the old version, the Test S3 button gave false positives, fixed in latest builds, so you can check that Test button again, then we can work through the troubleshooting steps.

403 is for unauthorized, so I'd start by double-checking the AWS credentials for S3 (I usually start with most permissive, then scale back).

**Comment by azevedown** [comment]
@leonstafford I reinstalled the plugin and the error persists. I configured the credentials with "S3FullAccess", updated the php to version 7.4, but the error message keeps showing up. I increased php and nginx timeout times but it didn't work.

The plugin is in version 6.6.7. The strangest thing is that most of the files he can deploy, but there are still some references missing and my website is broken.

I did a test with a new wordpress installation, just installed the wp2static plugin and was successful.

Some help?

**Comment by thegulshankumar** [comment]
"but there are still some references missing and my website is broken."

Please share logs of those broken URLs for sampling and addressing the issue. 

Also, please try once in .zip deploy.

Thanks

**Comment by quintcyril** [comment]
I had the same problem. Any updates on this?

**Comment by leonstafford** [comment]
@quintcyril replied to you on the wp.org forum - basically, uncheck the 4 boxes for disabling Public ACL in the S3 bucket's properties.
